import Foundation
import XCTest

@testable import SmeltRuntime

final class SmeltPointSelectorTests: XCTestCase {
    func testPinnedNumPyCandidatesAndFPSMatchSourceFixture() throws {
        let points = pointFixture()
        let mesh = try SmeltPointSelector.select(
            pointNormals: points,
            projection: .mesh
        )
        let condition = try SmeltPointSelector.select(
            pointNormals: points,
            projection: .condition
        )
        XCTAssertEqual(mesh.sourceIndices, decode(meshExpectedBase64, count: 512))
        XCTAssertEqual(
            condition.sourceIndices,
            decode(conditionExpectedBase64, count: 384)
        )
        XCTAssertEqual(mesh.pointNormals.count, 512 * 6)
        XCTAssertEqual(condition.pointNormals.count, 384 * 6)
        for (selectedPosition, sourceIndex) in mesh.sourceIndices.enumerated() {
            XCTAssertEqual(
                Array(mesh.pointNormals[(selectedPosition * 6)..<(selectedPosition * 6 + 6)]),
                Array(points[(sourceIndex * 6)..<(sourceIndex * 6 + 6)])
            )
        }
    }

    func testRejectsShapeAndNonFiniteInput() throws {
        XCTAssertThrowsError(
            try SmeltPointSelector.select(pointNormals: [], projection: .mesh)
        )
        var values = pointFixture()
        values[17] = .nan
        XCTAssertThrowsError(
            try SmeltPointSelector.select(pointNormals: values, projection: .condition)
        )
    }

    private func pointFixture() -> [Float] {
        var values = [Float](repeating: 0, count: 54_000 * 6)
        for index in 0..<54_000 {
            values[index * 6] = Float((index * 37) % 4_096 - 2_048) / 2_048
            values[index * 6 + 1] = Float((index * 109) % 8_192 - 4_096) / 4_096
            values[index * 6 + 2] = Float((index * 251) % 16_384 - 8_192) / 8_192
            values[index * 6 + 3] = Float((index * 13) % 256 - 128) / 128
            values[index * 6 + 4] = Float((index * 29) % 256 - 128) / 128
            values[index * 6 + 5] = Float((index * 61) % 256 - 128) / 128
        }
        return values
    }

    private func decode(_ encoded: String, count: Int) -> [Int] {
        let data = Data(base64Encoded: encoded, options: .ignoreUnknownCharacters)
        XCTAssertEqual(data?.count, count * 4)
        return data?.withUnsafeBytes { bytes in
            (0..<count).map { index in
                Int(
                    bytes.loadUnaligned(
                        fromByteOffset: index * 4,
                        as: UInt32.self
                    ).littleEndian
                )
            }
        } ?? []
    }

    private let meshExpectedBase64 =
        "2qoAAJxFAAADIAAAYiAAAN2FAADHFwAAPxMAAKuIAADmLQAA+ykAAKNnAACqywAAIUcAAE9pAACpKAAAVAwAAKZoAAB+ZgAARJkAAAdEAADIVwAAixkAALKOAADnlQAAhcwAAPGqAAC6ywAAkrMAAMq5AABszAAAwycAAD8wAAAdVgAACNEAAKNHAABJDgAANj4AACGoAAC6sAAAD8IAANBKAAA5HgAATmIAAFe0AAAVpQAA83QAAFJCAACVoAAAgrYAAN5kAAAZQQAAaVkAAM5+AABWxwAAKJAAAIq8AADvmQAAzrMAAFcoAACBWQAAoMYAAA4qAAC/kAAAGlIAAILNAABzmgAArZsAAO2IAAB3vgAATTUAAIahAAB3UgAAUkEAAAdlAADOygAAZg0AAMjLAABeeQAA98oAAKGEAACpUQAAc3IAAF8YAAB8fwAAyYwAABF2AAAJQwAABqsAAKCsAADyEAAA4V0AAAI5AADGtAAAVSYAAF9sAADeyAAAvKQAAO93AAA4zwAA37AAAFPSAADBmwAAC4gAADmBAACzggAAiKMAAHhDAADXUwAAJXUAAJa7AACnMAAA19EAADbNAAAsxQAAhMAAAD4cAAAKVQAAk00AAM0vAAAtpAAAOIMAACd+AACLxwAAvgEAAP8EAACfzAAAjhUAANtQAAD7ZAAAtGEAAFk4AAB+lAAARVUAANitAAA3VgAAtzgAAIGuAADrzQAASa4AANdWAADwvgAAEiYAAJtoAAAYrgAAIbUAANsLAADknwAA0sMAAP+KAACgQgAACEwAAFiIAAAjUwAA/MsAAKBdAAAFHAAAELsAACKiAAAErwAAriMAACirAADFfwAAa5cAAPOSAADNsgAA7ngAALcVAAAFEwAA9nkAAC8cAACuKQAAelkAALxxAABVHQAAdMoAAB1NAADmuwAAT38AAOBoAABdEgAA96AAAClBAADxwgAAgC8AADInAAArbgAA9XMAAAsAAACCigAAXgsAAE9vAAA3UQAAl4cAAAS7AAB2FwAA3lQAAKpqAADYOQAAbjMAAARxAADdfwAAZ0oAAPuLAABZRAAAdSIAAK/AAAD2CgAANFMAAE1YAAB7PQAA5HgAAPgNAAD8fgAAynoAAKsYAAAxGwAAAUcAAGt1AABUywAAOc4AAP2xAADVzAAAx6wAAEOtAAAjAAAAlx0AAGJJAAC/zAAA3mkAAPmAAABrMAAAMl4AAOoiAAC1jAAASNAAADfCAADWdwAACxwAAO2cAABklAAADKEAANjNAAC+eQAAMmgAAG3DAAAgyAAAkg8AAJrDAACtHgAA78UAAOBcAADOTQAAiTsAAFpjAACXdQAAcRUAAPqWAADJdQAAqB0AAGayAAApDQAA+rYAAPEpAACybQAAq5QAAPmVAADWyAAAhR4AAP+YAAATqwAAmC8AAJepAADxUQAAdzYAAHvAAABpbgAADmcAANsPAAB0TgAAMksAAMxaAABxDQAAy7EAAP/QAAAgegAA7n8AANfGAAAuDgAAGCkAADqFAACkdwAAhyoAANF6AACEfQAAYLcAACe3AABlXQAALXQAAEupAADctQAARxEAAKxIAABcFgAApRkAABmDAAAyyAAAx24AAL8HAADVmQAA7ssAAJrCAACyJQAAsAUAACPPAABeHwAAi7UAAI2dAABrIgAA2HAAAO8yAAB/NAAA9TsAAGEuAAC1OwAAM6sAAM6PAABIOwAAFqIAAC8/AAASAQAAcJ0AAEU4AAAMtwAAFW8AANa2AABfswAA7VUAAKx2AACfZQAAWrEAANS1AACsbgAAWNEAAB6yAAC2dQAAElEAAEFhAAAAlAAAkskAAJgaAACicgAAqkoAAJLLAABGAQAApbYAALE5AACkJAAAWLcAAPHMAABGOgAAGRMAAF8EAABJcQAABq4AALlCAADAngAAW5AAAPYjAABNJQAAFk8AAEIpAACMTQAA5SMAAItcAADXAgAAsx4AAJOMAABQIwAAE1IAAFAxAACOkwAA+aIAAGmlAABcLAAA8MkAAESbAABSHgAA8GUAAH6fAAB1yQAAay8AADOfAAB7OgAA22gAAB2uAAAyZAAAyUoAABAAAAA5nAAAc5wAALzNAACYDQAABAEAAB9CAADWLgAAraYAAK14AAAqsAAAksIAAPt6AADEeQAAsXoAAPOIAACyxwAAFJcAACvEAAArbAAAJgMAABfHAAC/WAAAgbgAADh0AAD4zAAAqwQAAFQ/AACbagAAUsAAABQEAABbtQAA4UIAAFkrAACEeQAAHWwAAA9WAADSEgAAY18AALBzAAAaaAAAta8AAMZTAACowAAAipYAAJWeAABivwAAxkUAAFdyAACffAAAP84AAN17AABXWAAAYW0AAO26AAB7RgAA3kEAAFeNAADPxQAAh60AAG+mAAAFlQAAhiAAAHFlAABDZwAAGpgAAJSsAABaMAAA5MkAAIwAAAAuGQAAV44AAL24AABKVQAACXsAACu9AAD6mAAAlbwAADeLAAC8IgAAE2QAAEBGAAAjaQAAcZsAAAjJAAA+rQAAuqAAAEXNAACRMQAAcxcAAFNgAAC6vAAAWQ8AAF+XAAC9MgAAZYgAAM23AADlSAAA04EAAMOIAABeeAAAaKQAAI0kAAB+EAAANjUAANalAABbpgAAtEoAAA4HAAD/UQAA1z4AAAmSAAByeQAApZ0AADzMAAA="
    private let conditionExpectedBase64 =
        "BLsAAKxuAACBDQAA6FMAAGFtAACAJgAAPosAAL55AAARdgAAJFUAAF+XAACDuQAADV4AAN6rAAAPVgAA2HAAAIGoAACJtAAAn8wAAOFpAAAldQAAcRUAAKpqAAB0ygAACNEAAPZ5AADyuAAA9ioAAL5ZAABcFgAAV7UAAIa4AABrMAAAHVYAAPEaAACEswAAOnwAAKR1AADOTQAAXCwAAMdzAAC7JwAAj7sAAKB5AACTAAAAzIwAAPzLAACrGAAAZg0AAGI6AABaqAAAs84AAHuDAABtCwAA+oQAAK14AABNlQAAoEIAAJFyAABVOgAAdhcAAACUAACCjQAADcMAAHOGAABSwAAAwWAAAGqXAAAyZAAAWLcAAKQNAAD4DQAAOZAAAIRNAABAHAAApqcAAE9pAABDZwAAksIAAPrBAABXjQAAxX8AAGC3AABZKwAA2UwAAGsvAAAYrgAAv1gAAOc4AAB+lAAAvTIAAP+YAADuZwAAipcAALixAACmTwAA9XMAAFtaAAD4zAAABqsAAOSfAAAKbwAABAEAANGjAAB0ggAAurAAAPmVAAC+CAAAiz0AAKqZAACoxQAAb6YAAIJCAACFHgAA3YUAAO1AAAD+eQAALxwAACt0AAB3nQAAVAwAALkNAACmaAAA/lQAAL2bAAA+JgAA3lAAAAAFAADNsgAAYZoAALiTAACnygAA8hAAAIufAABaMAAAlj0AABZPAAAZQQAA+4kAAIahAABbzwAAOYEAAEdqAAByQQAAurwAACwTAABpWAAAr7AAABrMAABEmQAAAD0AAJxFAADuAQAASG4AAJ+FAACyxwAAnzUAAN5UAAArIgAAMl4AAIvOAACLtQAAZYgAACOyAABUlAAAARcAAP2xAABmcwAAV3IAAKUfAAAgegAAZ2UAABd3AABHkAAAMT0AAMhXAAC3pQAAC4QAAK9+AAB6WQAAT28AAL4BAADfsAAA+ykAANGJAABLJgAAD8IAAOYZAAAcIwAAYiAAAFZYAACxEAAAW0EAACpdAAA2PgAAcJ0AAIUpAACtpgAA13QAALqgAABbhgAAbjMAAAqmAAAITAAAPMwAADmcAACvWwAAHEMAAM9CAACI0AAADr8AAKQkAAC2tQAARkkAABd4AAA/OQAAf8EAAOBcAADesgAA+m4AAH2dAACYQgAAK5QAAOtvAACSDwAAEBkAAHvAAAAQgQAAuAUAAIYYAAC8SwAAbcMAAF9sAAD4BQAAJScAALtzAAAjzwAAiKMAAAMqAADCYwAA588AAJcdAADozAAAwVUAAC0pAACYJwAAU9IAAK03AAAvPwAADmcAALKNAAANawAA0IEAACGlAADwbQAAXEsAAC6nAADgiAAAfFgAADbNAADQeQAAQw8AACJ5AAAeDwAAqwQAAFl0AABwPQAAOM8AALikAACMAAAA98oAAFbHAAC7XQAAesUAAFuQAAB4UgAAc1cAALmBAADvtAAAOGcAAAiKAABaNgAAebIAAFjRAACzggAAHFoAAGUyAAA4gwAAEq8AAFUdAACxOQAAHgUAAO/FAACqUQAA55cAAJLJAAD1qQAAwXgAALM3AABYeQAAM0AAABSXAACBWQAAxkUAADB6AAD5ogAA2M0AADclAADB0gAAXh8AAKJyAADtugAA+4sAABl/AAByuAAAdr0AAB0YAAAGjgAA6V0AAKo1AABGYAAAlMEAAKRcAAAFHAAAriMAAAmSAAAwtQAAga4AAPHMAABhjAAA12EAAPJUAAAHAwAAAJgAANw5AAD1bgAAlSYAAGzMAAAZEwAA21AAAOumAADWtgAAZoMAAFsDAABEKAAAc3IAAII7AAABfgAA2x0AAPq2AAC6nAAA4MoAALMeAAAHuAAAKxkAAIXMAACsSwAAt88AAPUJAABzoAAAyJwAADrGAADwyQAAlRMAAIQXAAD0pgAAr8AAAFSFAAC2zAAAyrkAANitAAAQKAAAN1EAAHXJAADeQQAAYTMAAKkNAADHzAAAPzwAAMAnAADxqgAAhwIAAP2FAACgnwAA"
}
