// TopLevelEmitter — Generates the complete encodeDecodeStep Swift function.
//
// This is the top-level code generator that ties together the embedding,
// DeltaNet/Attention plugins, FFN, and final norm/LM head/argmax into
// a single generated function. The output is a complete Swift source file
// that can be compiled into the .smeltpkg.

/// Generates the complete model dispatch function.
public struct TopLevelEmitter {

    /// Result of code generation: Swift source + binary dispatch table + pipeline names.
    public struct GenerateResult {
        /// Complete Swift source for SmeltGenerated.swift.
        public let source: String
        /// Binary dispatch records for dispatches.bin.
        public let dispatchRecords: [SmeltDispatchRecord]
        /// Optional debug boundaries for tracing decode.
        public let traceMarkers: [SmeltTraceMarker]
        /// Full pipeline name list for manifest (base + function-constant-specialized).
        /// Specialized entries use "name:cols:groupSize" format.
        public let pipelineNames: [String]
        /// Package-local concrete Metal function names appended to the manifest.
        public let namedPipelineNames: [String]
        /// Final named pipeline dispatches with planned route metadata when available.
        let namedPipelineUses: [SmeltNamedPipelineUse]
        /// Rewrites applied while optimizing the decode dispatch IR.
        public let optimizationStats: SmeltOptimizationStats
        /// True iff this codegen produced a headless trunk (embeddings-in / hidden-out, no LM head)
        /// — the DenseTrunkEmitter path. Stamped into `SmeltManifest.headlessTrunkABI` so the runtime's
        /// trunk-API gate keys off an explicit marker, not the fp32 port dtype (U3 activation axis).
        public let isHeadlessTrunkABI: Bool
    }

    static func generate(
        ir: SmeltModelIR,
        compilationPlan: SmeltCompilationPlan,
        traceMode: SmeltTraceMode = .full
    ) throws -> GenerateResult {
        try generate(
            ir: ir,
            plan: compilationPlan.bufferPlan,
            compilationPlan: compilationPlan,
            traceMode: traceMode
        )
    }

    static func generate(
        ir: SmeltModelIR,
        plan bufferPlan: SmeltBufferPlan,
        compilationPlan: SmeltCompilationPlan,
        traceMode: SmeltTraceMode = .full
    ) throws -> GenerateResult {
        try generatePlanned(
            ir: ir,
            plan: bufferPlan,
            plannedWeightLayout: compilationPlan.plannedWeightEntries,
            traceMode: traceMode,
            kernelPlan: compilationPlan.kernelPlan
        )
    }

    /// Generate the decode function as Swift source + binary dispatch table.
    ///
    /// - Parameters:
    ///   - ir: Validated model IR.
    ///   - plan: Buffer plan with slot indices.
    ///   - weightLayout: Weight entries for byte offsets.
    /// - Returns: Swift source and binary dispatch records.
    public static func generate(
        ir: SmeltModelIR,
        plan: SmeltBufferPlan,
        weightLayout: [SmeltWeightEntry],
        traceMode: SmeltTraceMode = .full,
        kernelPlan: SmeltKernelPlan? = nil
    ) throws -> GenerateResult {
        let compilationPlan = try SmeltCompiler.planCompilation(
            ir: ir,
            weightLayout: weightLayout,
            kernelPlan: kernelPlan
        )
        return try generate(
            ir: ir,
            plan: plan,
            compilationPlan: compilationPlan,
            traceMode: traceMode
        )
    }

    private static func generatePlanned(
        ir: SmeltModelIR,
        plan: SmeltBufferPlan,
        plannedWeightLayout weightLayout: [SmeltWeightEntry],
        traceMode: SmeltTraceMode,
        kernelPlan: SmeltKernelPlan
    ) throws -> GenerateResult {
        // Port topology selects the graph; activation/weight dtype select
        // operation-family cells inside that graph.
        if ir.config.portTopology == .embeddingsInHiddenOut {
            return try DenseTrunkEmitter.generate(
                ir: ir, plan: plan, weightLayout: weightLayout)
        }
        let cfg = ir.config
        let hidden = cfg.hiddenSize
        let weightsSlot = SmeltFixedSlot.weights.rawValue
        let groupSize = ir.quantization.groupSize
        let weightEntries = Dictionary(
            uniqueKeysWithValues: weightLayout.map { ($0.name, $0) }
        )

        let fusionPlanner = SmeltFusionPlanner.planned(kernelPlan: kernelPlan)
        var emitter = SmeltCodeEmitter(
            indent: 4,
            traceMarkersEnabled: traceMode.recordsTraceMarkers,
            fusionPlanner: fusionPlanner
        )
        var lines: [String] = []

        // --- File header ---
        lines.append("// --- Generated by smelt build. Do not edit. ---")
        lines.append("import Metal")
        lines.append("")

        // --- Function signature ---
        lines.append("@inline(__always)")
        lines.append("internal func encodeDecodeStep(")
        lines.append(
            "    _ enc: MTLComputeCommandEncoder,"
        )
        lines.append(
            "    _ p: UnsafeBufferPointer<MTLComputePipelineState>,"
        )
        lines.append(
            "    _ b: UnsafeBufferPointer<MTLBuffer>,"
        )
        lines.append("    position: Int32,")
        lines.append("    tokenId: Int32,")
        lines.append("    cacheSeqCapacity: UInt32")
        lines.append(") {")

        // --- Bounds check ---
        lines.append(emitter.emitComment(
            "Runtime bounds check"
        ))
        lines.append(emitter.emitRaw(
            "precondition(position >= 0 && UInt32(position) < cacheSeqCapacity, "
                + "\"position out of range [0, \\(cacheSeqCapacity))\")"
        ))
        lines.append(emitter.emitRaw(
            "precondition(tokenId >= 0 && tokenId < \(cfg.vocabSize), "
                + "\"tokenId out of range [0, \(cfg.vocabSize))\")"
        ))
        lines.append(emitter.emitBlank())

        // --- Update dynamic slots ---
        lines.append(emitter.emitComment("Update dynamic slots"))
        lines.append(emitter.emitRaw(
            "b[\(plan.tokenIdSlot)].contents()"
                + ".storeBytes(of: tokenId, as: Int32.self)"
        ))
        lines.append(emitter.emitRaw(
            "b[\(plan.positionSlot)].contents()"
                + ".storeBytes(of: position, as: Int32.self)"
        ))
        // --- Embedding or runtime-supplied fused input ---
        if cfg.inputFusion == nil {
            let embedEntry = try requireWeight(
                SmeltCanonicalTensorNames.embedTokens, from: weightEntries
            )
        // Branch on the ENTRY dtype (the manifest truth), not the config
        // flag — a quantized entry routed to the fp16 gather would read
        // packed bytes as fp16 (Trap #3). Group size resolves from the
        // entry first (per-tensor group sizes are possible).
        if embedEntry.dtype == .u4Lut,
           let lutOff = embedEntry.lutOffset
        {
            lines += try emitter.emitLUTEmbeddingGather(
                indicesSlot: weightsSlot, indicesOffset: embedEntry.offset,
                lutSlot: weightsSlot, lutOffset: lutOff,
                tokenIdSlot: plan.tokenIdSlot,
                outputSlot: SmeltFixedSlot.hiddenA.rawValue,
                hiddenSize: hidden,
                groupSize: embedEntry.groupSize ?? ir.quantization.groupSize,
                comment: "Embedding → hiddenA (quantized gather)"
            )
        } else if embedEntry.dtype == .affineU4,
                  let scalesOff = embedEntry.scalesOffset,
                  let biasesOff = embedEntry.biasesOffset
        {
            lines += try emitter.emitAffineEmbeddingGather(
                weightsSlot: weightsSlot, weightsOffset: embedEntry.offset,
                scalesSlot: weightsSlot, scalesOffset: scalesOff,
                biasesSlot: weightsSlot, biasesOffset: biasesOff,
                tokenIdSlot: plan.tokenIdSlot,
                outputSlot: SmeltFixedSlot.hiddenA.rawValue,
                hiddenSize: hidden,
                groupSize: embedEntry.groupSize ?? ir.quantization.groupSize,
                comment: "Embedding → hiddenA (affine quantized gather)"
            )
        } else if embedEntry.dtype == .binary1 || embedEntry.dtype == .ternary2 {
            lines += try emitter.emitSignedEmbeddingGather(
                weightEntry: embedEntry,
                weightsSlot: weightsSlot,
                tokenIdSlot: plan.tokenIdSlot,
                outputSlot: SmeltFixedSlot.hiddenA.rawValue,
                hiddenSize: hidden,
                comment: "Embedding → hiddenA (native signed gather)"
            )
        } else if embedEntry.dtype == .turboQuantH,
                  let codebookOff = embedEntry.codebookOffset,
                  let codesPerRow = embedEntry.packedRowStride
        {
            lines += try emitter.emitTurboQuantHEmbeddingGather(
                codesSlot: weightsSlot, codesOffset: embedEntry.offset,
                codebookSlot: weightsSlot, codebookOffset: codebookOff,
                tokenIdSlot: plan.tokenIdSlot,
                outputSlot: SmeltFixedSlot.hiddenA.rawValue,
                hiddenSize: hidden, codesPerRow: codesPerRow,
                comment: "Embedding → hiddenA (turbo_quant_h gather)"
            )
        } else {
            lines += try emitter.emitEmbeddingGather(
                weightSlot: weightsSlot, weightOffset: embedEntry.offset,
                tokenIdSlot: plan.tokenIdSlot,
                outputSlot: SmeltFixedSlot.hiddenA.rawValue,
                hiddenSize: hidden,
                comment: "Embedding → hiddenA"
            )
        }
            emitter.recordTraceMarker(
                label: "embed_out",
                bufferSlot: SmeltFixedSlot.hiddenA.rawValue
            )
            lines.append(emitter.emitBlank())
        }

        if cfg.hiddenSizePerLayerInput > 0 {
            lines += try emitPerLayerInputsSetup(
                config: cfg,
                weightEntries: weightEntries,
                weightsSlot: weightsSlot,
                tokenIdSlot: plan.tokenIdSlot,
                groupSize: groupSize,
                quantizeEmbedding: ir.quantization.quantizeEmbedding,
                emitter: &emitter
            )
            lines.append(emitter.emitBlank())
        }

        // Model-agnostic runtime feature fusion. `hiddenB` carries the
        // concatenated source rows; the compiler owns norm and projection.
        if let fusion = cfg.resolvedInputFusion {
            if fusion.normalizeSources {
                for source in 0 ..< fusion.sourceCount {
                    let byteOffset = UInt64(source * fusion.sourceWidth * 2)
                    let normEntry = try requireWeight(
                        "input_fusion_norm_\(source)_weight", from: weightEntries
                    )
                    lines += try emitter.emitRMSNorm1PW(
                        inputSlot: SmeltFixedSlot.hiddenB.rawValue,
                        weightSlot: weightsSlot,
                        weightOffset: normEntry.offset,
                        outputSlot: SmeltFixedSlot.hiddenB.rawValue,
                        dim: fusion.sourceWidth,
                        eps: cfg.rmsEps,
                        inputOffset: byteOffset,
                        outputOffset: byteOffset,
                        comment: "Input fusion source \(source) norm"
                    )
                }
            }
            let preEntry = try requireWeight("pre_projection_weight", from: weightEntries)
            lines.append(emitter.emitComment(
                cfg.backboneHiddenSize != nil
                    ? "Pre-projection (drafter input → drafter hidden)"
                    : "Pre-projection (fused input → stack hidden)"
            ))
            lines += try emitter.emitMatvec(
                weightEntry: preEntry,
                weightsSlot: weightsSlot,
                inputSlot: SmeltFixedSlot.hiddenB.rawValue,
                outputSlot: SmeltFixedSlot.hiddenA.rawValue,
                rows: hidden, cols: fusion.concatenatedWidth, groupSize: groupSize,
                comment: "Pre-projection matmul"
            )
            emitter.recordTraceMarker(
                label: "pre_projection_out",
                bufferSlot: SmeltFixedSlot.hiddenA.rawValue
            )
            lines.append(emitter.emitBlank())
        }

        // --- Double-buffer tracking ---
        lines.append(emitter.emitComment(
            "Double-buffer: cur=hiddenA, alt=hiddenB. Swap after each residual add."
        ))
        lines.append(emitter.emitRaw(
            "var cur = \(SmeltFixedSlot.hiddenA.rawValue)"
        ))
        lines.append(emitter.emitRaw(
            "var alt = \(SmeltFixedSlot.hiddenB.rawValue)"
        ))
        lines.append(emitter.emitBlank())

        // --- Layer loop (unrolled at compile time) ---
        let layers = ir.layerPattern.expanded
        var deltaIdx = 0
        var attnIdx = 0

        let normOutSlot = SmeltFixedSlot.normOutBuf.rawValue

        for (layerIndex, layerType) in layers.enumerated() {
            lines.append(emitter.emitComment(
                "--- Layer \(layerIndex) (\(layerType.rawValue)) ---"
            ))

            // Input layernorm: cur → normOutBuf
            let inputNormName =
                "layers_\(layerIndex)_input_layernorm_weight"
            lines += try emitter.emitRMSNorm1PWVar(
                inputSlotVar: "cur",
                weightSlot: weightsSlot,
                weightOffset: try requireWeight(inputNormName, from: weightEntries).offset,
                outputSlot: normOutSlot,
                dim: hidden, eps: cfg.rmsEps,
                comment: "Input layernorm"
            )
            emitter.recordTraceMarker(
                label: "L\(layerIndex).input_norm",
                bufferSlot: SmeltFixedSlot.normOutBuf.rawValue
            )
            let projectionSource: SmeltCAMIR.ProjectionSource = layerType == .delta
                ? .deltaInput : .attentionInput
            if let bank = cfg.projectionBanks.first(where: {
                $0.source == projectionSource && $0.activationView != nil
            }),
               bank.usesActivationView(at: layerIndex),
               let activationView = bank.activationView {
                guard plan.projectionActivationPlanesSlot >= 0,
                      plan.projectionActivationScalesSlot >= 0 else {
                    throw SmeltEmitError.missingConfig(
                        detail: "projection activation view buffers are missing")
                }
                lines += try emitter.emitSignedActivationView(
                    activationView,
                    inputSlot: normOutSlot,
                    planesSlot: plan.projectionActivationPlanesSlot,
                    scalesSlot: plan.projectionActivationScalesSlot,
                    cols: hidden,
                    comment: "CAM \(projectionSource.rawValue) activation view"
                )
            }

            // Layer-specific dispatch
            switch layerType {
            case .delta:
                lines += try DeltaNetPlugin.emitLayer(
                    layerIndex: layerIndex,
                    deltaIndex: deltaIdx,
                    config: cfg,
                    plan: plan,
                    weightEntries: weightEntries,
                    weightsSlot: weightsSlot,
                    groupSize: groupSize,
                    traceMode: traceMode,
                    emitter: &emitter
                )
                deltaIdx += 1

            case .attention:
                lines += try AttentionPlugin.emitLayer(
                    layerIndex: layerIndex,
                    attnIndex: attnIdx,
                    layerType: .attention,
                    config: cfg,
                    plan: plan,
                    weightEntries: weightEntries,
                    weightsSlot: weightsSlot,
                    groupSize: groupSize,
                    kernelPlan: kernelPlan,
                    emitter: &emitter,
                    sharedKVSourceAttnIndex: ir.kvSharedSourceAttentionIndex(forGlobalLayerIndex: layerIndex),
                    traceMode: traceMode
                )
                attnIdx += 1

            case .sliding, .global:
                let attn = try requireAttentionConfig(
                    for: layerType,
                    from: cfg
                )
                let ropeSlots = try resolveRoPESlots(
                    for: attn,
                    layerType: layerType,
                    config: cfg,
                    plan: plan
                )
                lines += try AttentionPlugin.emitLayer(
                    layerIndex: layerIndex,
                    attnIndex: attnIdx,
                    layerType: layerType,
                    config: cfg,
                    plan: plan,
                    weightEntries: weightEntries,
                    weightsSlot: weightsSlot,
                    groupSize: groupSize,
                    kernelPlan: kernelPlan,
                    emitter: &emitter,
                    attnOverride: attn,
                    ropeCosSlotOverride: ropeSlots.cos,
                    ropeSinSlotOverride: ropeSlots.sin,
                    sharedKVSourceAttnIndex: ir.kvSharedSourceAttentionIndex(forGlobalLayerIndex: layerIndex),
                    traceMode: traceMode
                )
                attnIdx += 1
            }

            // Residual add: cur + normOutBuf → alt
            if cfg.blockTopology == .standard {
                lines += try emitter.emitElementwiseAddVar(
                    inputAVar: "cur", inputBSlot: normOutSlot,
                    outputVar: "alt", count: hidden,
                    comment: "Residual add"
                )

                lines.append(emitter.emitRaw("swap(&cur, &alt)"))
                emitter.recordSwap()
                emitter.recordTraceMarker(
                    label: "L\(layerIndex).mid",
                    bufferSlot: SmeltFixedSlot.hiddenB.rawValue
                )
                lines.append(emitter.emitBlank())

                let postNormName =
                    "layers_\(layerIndex)_post_attention_layernorm_weight"
                lines += try emitter.emitRMSNorm1PWVar(
                    inputSlotVar: "cur",
                    weightSlot: weightsSlot,
                    weightOffset: try requireWeight(postNormName, from: weightEntries).offset,
                    outputSlot: normOutSlot,
                    dim: hidden, eps: cfg.rmsEps,
                    comment: "Post-attention layernorm"
                )
                emitter.recordTraceMarker(
                    label: "L\(layerIndex).post_norm",
                    bufferSlot: SmeltFixedSlot.normOutBuf.rawValue
                )

                lines += try emitFFN(
                    layerIndex: layerIndex,
                    config: cfg,
                    weightEntries: weightEntries,
                    weightsSlot: weightsSlot,
                    groupSize: groupSize,
                    ffnDownFp32Slot: plan.ffnDownFp32Slot,
                    projectionActivationPlanesSlot: plan.projectionActivationPlanesSlot,
                    projectionActivationScalesSlot: plan.projectionActivationScalesSlot,
                    kernelPlan: kernelPlan,
                    traceMode: traceMode,
                    emitter: &emitter
                )

                lines += try emitter.emitElementwiseAddVar(
                    inputAVar: "cur",
                    inputBSlot: SmeltFixedSlot.ffnDownBuf.rawValue,
                    outputVar: "alt", count: hidden,
                    comment: "FFN residual add"
                )
            } else {
                let postAttentionNormName =
                    "layers_\(layerIndex)_post_attention_layernorm_weight"
                let postAttentionNormOffset = try requireWeight(
                    postAttentionNormName,
                    from: weightEntries
                ).offset
                if traceMode.usesStrippedOptimizations,
                   let fused = try emitter.emitRMSNorm1PWAddVarIfPossible(
                    inputSlot: normOutSlot,
                    weightSlot: weightsSlot,
                    weightOffset: postAttentionNormOffset,
                    residualSlotVar: "cur",
                    outputSlotVar: "alt",
                    dim: hidden,
                    eps: cfg.rmsEps,
                    comment: "Post-attention layernorm + residual add (fused)"
                   )
                {
                    lines += fused
                } else {
                    lines += try emitter.emitRMSNorm1PW(
                        inputSlot: normOutSlot,
                        weightSlot: weightsSlot,
                        weightOffset: postAttentionNormOffset,
                        outputSlot: SmeltFixedSlot.ffnDownBuf.rawValue,
                        dim: hidden, eps: cfg.rmsEps,
                        comment: "Post-attention layernorm"
                    )
                    emitter.recordTraceMarker(
                        label: "L\(layerIndex).post_attn_norm",
                        bufferSlot: SmeltFixedSlot.ffnDownBuf.rawValue
                    )

                    lines += try emitter.emitElementwiseAddVar(
                        inputAVar: "cur",
                        inputBSlot: SmeltFixedSlot.ffnDownBuf.rawValue,
                        outputVar: "alt", count: hidden,
                        comment: "Residual add"
                    )
                }

                lines.append(emitter.emitRaw("swap(&cur, &alt)"))
                emitter.recordSwap()
                emitter.recordTraceMarker(
                    label: "L\(layerIndex).mid",
                    bufferSlot: SmeltFixedSlot.hiddenB.rawValue
                )
                lines.append(emitter.emitBlank())

                let preFeedforwardNormName =
                    "layers_\(layerIndex)_pre_feedforward_layernorm_weight"
                let preFeedforwardNormOffset = try requireWeight(
                    preFeedforwardNormName,
                    from: weightEntries
                ).offset
                if traceMode.usesStrippedOptimizations,
                   let fused = try emitStrippedNormScaleGeGLUFFNIfPossible(
                    layerIndex: layerIndex,
                    config: cfg,
                    weightEntries: weightEntries,
                    weightsSlot: weightsSlot,
                    groupSize: groupSize,
                    preFeedforwardNormOffset: preFeedforwardNormOffset,
                    ffnDownFp32Slot: plan.ffnDownFp32Slot,
                    emitter: &emitter
                   )
                {
                    lines += fused
                } else {
                    lines += try emitter.emitRMSNorm1PWVar(
                        inputSlotVar: "cur",
                        weightSlot: weightsSlot,
                        weightOffset: preFeedforwardNormOffset,
                        outputSlot: normOutSlot,
                        dim: hidden, eps: cfg.rmsEps,
                        comment: "Pre-feedforward layernorm"
                    )
                    emitter.recordTraceMarker(
                        label: "L\(layerIndex).pre_ffn_norm",
                        bufferSlot: SmeltFixedSlot.normOutBuf.rawValue
                    )

                    lines += try emitFFN(
                        layerIndex: layerIndex,
                        config: cfg,
                        weightEntries: weightEntries,
                        weightsSlot: weightsSlot,
                        groupSize: groupSize,
                        ffnDownFp32Slot: plan.ffnDownFp32Slot,
                        projectionActivationPlanesSlot: plan.projectionActivationPlanesSlot,
                        projectionActivationScalesSlot: plan.projectionActivationScalesSlot,
                        kernelPlan: kernelPlan,
                        traceMode: traceMode,
                        emitter: &emitter
                    )
                }

                let postFeedforwardNormName =
                    "layers_\(layerIndex)_post_feedforward_layernorm_weight"
                let postFeedforwardNormOffset = try requireWeight(
                    postFeedforwardNormName,
                    from: weightEntries
                ).offset
                let downEntryForPostNorm = try requireWeight(
                    SmeltKernelConsumerNaming.ffnDownWeight(layerIndex: layerIndex),
                    from: weightEntries
                )
                let postFeedforwardInputIsFP32 = plan.ffnDownFp32Slot >= 0
                    && downEntryForPostNorm.dtype == .fp16
                let usedFusedPostFeedforwardNormAdd: Bool
                if traceMode.usesStrippedOptimizations,
                   !postFeedforwardInputIsFP32,
                   let fused = try emitter.emitRMSNorm1PWAddVarIfPossible(
                    inputSlot: SmeltFixedSlot.ffnDownBuf.rawValue,
                    weightSlot: weightsSlot,
                    weightOffset: postFeedforwardNormOffset,
                    residualSlotVar: "cur",
                    outputSlotVar: "alt",
                    dim: hidden,
                    eps: cfg.rmsEps,
                    comment: "Post-feedforward layernorm + residual add (fused)"
                   )
                {
                    lines += fused
                    usedFusedPostFeedforwardNormAdd = true
                } else if postFeedforwardInputIsFP32 {
                    lines += try emitter.emitRMSNorm1PWFromFP32(
                        inputSlot: plan.ffnDownFp32Slot,
                        weightSlot: weightsSlot,
                        weightOffset: postFeedforwardNormOffset,
                        outputSlot: normOutSlot,
                        dim: hidden, eps: cfg.rmsEps,
                        comment: "Post-feedforward layernorm (FP32 input)"
                    )
                    usedFusedPostFeedforwardNormAdd = false
                } else {
                    lines += try emitter.emitRMSNorm1PW(
                        inputSlot: SmeltFixedSlot.ffnDownBuf.rawValue,
                        weightSlot: weightsSlot,
                        weightOffset: postFeedforwardNormOffset,
                        outputSlot: normOutSlot,
                        dim: hidden, eps: cfg.rmsEps,
                        comment: "Post-feedforward layernorm"
                    )
                    usedFusedPostFeedforwardNormAdd = false
                }
                if !usedFusedPostFeedforwardNormAdd {
                    if !traceMode.usesStrippedOptimizations || postFeedforwardInputIsFP32 {
                        emitter.recordTraceMarker(
                            label: "L\(layerIndex).post_ffn_norm",
                            bufferSlot: SmeltFixedSlot.normOutBuf.rawValue
                        )
                    }

                    lines += try emitter.emitElementwiseAddVar(
                        inputAVar: "cur",
                        inputBSlot: SmeltFixedSlot.normOutBuf.rawValue,
                        outputVar: "alt", count: hidden,
                        comment: "FFN residual add"
                    )
                }
                emitter.recordTraceMarker(
                    label: "L\(layerIndex).pre_per_layer_branch",
                    bufferSlot: SmeltFixedSlot.hiddenA.rawValue
                )

                if cfg.hiddenSizePerLayerInput > 0 {
                    lines += try emitPerLayerResidualBranch(
                        layerIndex: layerIndex,
                        config: cfg,
                        weightEntries: weightEntries,
                        weightsSlot: weightsSlot,
                        groupSize: groupSize,
                        emitter: &emitter,
                        traceMode: traceMode
                    )
                }
            }

            lines.append(emitter.emitRaw("swap(&cur, &alt)"))
            emitter.recordSwap()
            emitter.recordTraceMarker(
                label: "L\(layerIndex).out",
                bufferSlot: SmeltFixedSlot.hiddenA.rawValue
            )
            lines.append(emitter.emitBlank())
        }

        // --- Final norm / LM head ---
        let finalNormOffset = try requireWeight("norm_weight", from: weightEntries).offset
        let lmHeadEntry = cfg.tiedLMHead
            ? try requireWeight(SmeltCanonicalTensorNames.embedTokens, from: weightEntries)
            : try requireWeight("lm_head_weight", from: weightEntries)
        let lmHeadComment = cfg.tiedLMHead
            ? "LM head (tied to embed_tokens)"
            : "LM head (separate weight)"
        let lmHeadActivationView = cfg.projectionBank(
            source: .lmHeadInput,
            containing: [.lmHead]
        )?.activationView
        let supportsLMHeadActivationView: Bool
        switch (lmHeadEntry.dtype, lmHeadActivationView) {
        case (.binary1, .some):
            supportsLMHeadActivationView = true
        case (.ternary2, .some(.signedBitplanesI4)),
             (.ternary2, .some(.signedBitplanesI5)),
             (.ternary2, .some(.signedBitplanesI6)):
            supportsLMHeadActivationView = true
        default:
            supportsLMHeadActivationView = false
        }

        if let cluster = cfg.clusterEmbedder {
            // Sparse cluster lm_head. Replaces the dense matvec over the
            // full vocab with a top-k centroid gather
            // (~64x fewer dot-products at 2048 centroids / top_k 32).
            //
            // Step 1: final norm cur → normOutBuf (kept separate from
            //         the fused-matvec path because the cluster
            //         dispatch reads normOutBuf directly).
            // Step 2: matvec — centroids_weight × normOutBuf →
            //         centroidLogitsBuf [num_centroids].
            // Step 3: clusterSparseLMHead — topk centroids + gather
            //         (top_k * tokens_per_cluster) lm_head rows +
            //         dot-product with normOutBuf + scatter into
            //         logitsBuf with `-inf` everywhere else. Single
            //         monolithic Metal kernel in Resources/Shaders/cluster.metal.
            //
            // The argmax block below still runs unchanged — it reads
            // logitsBuf the same way.
            lines += try emitter.emitRMSNorm1PWVar(
                inputSlotVar: "cur",
                weightSlot: weightsSlot,
                weightOffset: finalNormOffset,
                outputSlot: normOutSlot,
                dim: hidden, eps: cfg.rmsEps,
                comment: "Final norm (cluster lm_head path)"
            )
            emitter.recordTraceMarker(
                label: "final_norm",
                bufferSlot: SmeltFixedSlot.normOutBuf.rawValue
            )

            let centroidsEntry = try requireWeight(
                "masked_embedding_centroids_weight", from: weightEntries
            )
            lines += try emitter.emitMatvec(
                weightEntry: centroidsEntry,
                weightsSlot: weightsSlot,
                inputSlot: normOutSlot,
                outputSlot: SmeltFixedSlot.centroidLogitsBuf.rawValue,
                rows: cluster.numCentroids, cols: hidden, groupSize: groupSize,
                comment: "Centroid projection (cluster lm_head)"
            )
            emitter.recordTraceMarker(
                label: "centroid_logits",
                bufferSlot: SmeltFixedSlot.centroidLogitsBuf.rawValue
            )

            let tokenOrderingEntry = try requireWeight(
                SmeltCanonicalTensorNames.maskedEmbeddingTokenOrdering,
                from: weightEntries
            )
            let tokensPerCluster = cluster.tokensPerCluster(vocabSize: cfg.vocabSize)
            lines += try emitter.emit(SmeltDispatch(
                pipeline: .clusterSparseLMHead,
                buffers: [
                    SmeltBufferBinding(
                        slot: SmeltFixedSlot.centroidLogitsBuf.rawValue, index: 0
                    ),
                    SmeltBufferBinding(
                        slot: weightsSlot, offset: lmHeadEntry.offset, index: 1
                    ),
                    SmeltBufferBinding(slot: normOutSlot, index: 2),
                    SmeltBufferBinding(
                        slot: weightsSlot, offset: tokenOrderingEntry.offset, index: 3
                    ),
                    SmeltBufferBinding(
                        slot: SmeltFixedSlot.logitsBuf.rawValue, index: 4
                    ),
                ],
                constants: [
                    SmeltConstantBinding(
                        expression: "\(cluster.numCentroids)", type: .uint32, index: 5
                    ),
                    SmeltConstantBinding(
                        expression: "\(cluster.topK)", type: .uint32, index: 6
                    ),
                    SmeltConstantBinding(
                        expression: "\(cfg.vocabSize)", type: .uint32, index: 7
                    ),
                    SmeltConstantBinding(
                        expression: "\(hidden)", type: .uint32, index: 8
                    ),
                    SmeltConstantBinding(
                        expression: "\(tokensPerCluster)", type: .uint32, index: 9
                    ),
                    // Apply softcap inside the kernel — TopLevelEmitter
                    // skips the generic logit-cap pass on the cluster
                    // path so -inf sentinels stay -inf. 0 disables.
                    SmeltConstantBinding(
                        expression: "\(cfg.logitCap ?? 0)", type: .float32, index: 10
                    ),
                ],
                dispatch: .threadgroups(
                    // Grid dim: one threadgroup per centroid. Each
                    // threadgroup independently determines whether its
                    // centroid is in the top-k via a rank computation
                    // over centroidLogitsBuf, then writes either a
                    // dot-product score (selected) or -inf (not
                    // selected) for each of its tokensPerCluster
                    // logits. tgWidth = tokensPerCluster so one thread
                    // per vocab slot in the cluster.
                    width: cluster.numCentroids, height: 1, depth: 1,
                    tgWidth: min(tokensPerCluster, 256), tgHeight: 1, tgDepth: 1
                ),
                comment: "Cluster sparse LM head (top-k=\(cluster.topK) of \(cluster.numCentroids))"
            ))
            emitter.recordTraceMarker(
                label: "cluster_lm_head_logits",
                bufferSlot: SmeltFixedSlot.logitsBuf.rawValue
            )
        } else if let lmHeadActivationView,
                  supportsLMHeadActivationView,
                  plan.projectionActivationPlanesSlot >= 0,
                  plan.projectionActivationScalesSlot >= 0 {
            lines += try emitter.emitRMSNorm1PWVar(
                inputSlotVar: "cur",
                weightSlot: weightsSlot,
                weightOffset: finalNormOffset,
                outputSlot: normOutSlot,
                dim: hidden, eps: cfg.rmsEps,
                comment: "Final norm"
            )
            emitter.recordTraceMarker(
                label: "final_norm",
                bufferSlot: SmeltFixedSlot.normOutBuf.rawValue
            )
            guard let headLines = try emitter.emitSignedBitplaneProjectionIfPossible(
                view: lmHeadActivationView,
                weightEntry: lmHeadEntry,
                weightsSlot: weightsSlot,
                inputSlot: normOutSlot,
                planesSlot: plan.projectionActivationPlanesSlot,
                activationScalesSlot: plan.projectionActivationScalesSlot,
                outputSlot: SmeltFixedSlot.logitsBuf.rawValue,
                rows: cfg.vocabSize,
                cols: hidden,
                producerComment: "CAM lm-head-input activation view",
                projectionComment: lmHeadComment
            ) else {
                throw SmeltEmitError.unsupported(
                    detail: "declared LM-head activation view has no signed lowering"
                )
            }
            lines += headLines
        } else if traceMode.usesStrippedOptimizations,
           let fusedFinal = try emitter.emitNormScaleAffineMatvecIfPossible(
                normInputSlotVar: "cur",
                normWeightSlot: weightsSlot,
                normWeightOffset: finalNormOffset,
                normOutputSlot: normOutSlot,
                weightEntry: lmHeadEntry,
                weightsSlot: weightsSlot,
                outputSlot: SmeltFixedSlot.logitsBuf.rawValue,
                rows: cfg.vocabSize,
                cols: hidden,
                groupSize: groupSize,
                comment: lmHeadComment
           )
        {
            lines += fusedFinal
        } else {
            lines += try emitter.emitRMSNorm1PWVar(
                inputSlotVar: "cur",
                weightSlot: weightsSlot,
                weightOffset: finalNormOffset,
                outputSlot: normOutSlot,
                dim: hidden, eps: cfg.rmsEps,
                comment: "Final norm"
            )
            emitter.recordTraceMarker(
                label: "final_norm",
                bufferSlot: SmeltFixedSlot.normOutBuf.rawValue
            )

            lines += try emitter.emitMatvec(
                weightEntry: lmHeadEntry,
                weightsSlot: weightsSlot,
                inputSlot: normOutSlot,
                outputSlot: SmeltFixedSlot.logitsBuf.rawValue,
                rows: cfg.vocabSize, cols: hidden, groupSize: groupSize,
                comment: lmHeadComment
            )
        }

        // Logit capping pass runs on every position of logitsBuf —
        // including the -inf sentinels the cluster sparse lm_head
        // scatters into non-selected vocab rows. `cap * tanh(-inf /
        // cap) == -cap`, a finite number, which silently unmasks
        // every non-candidate before argmax/sampling. Skip the pass
        // for cluster packages; the cluster kernel can apply softcap
        // inside its own dot-product path (unit 2c3 implementation
        // detail).
        if let logitCap = cfg.logitCap, cfg.clusterEmbedder == nil {
            lines += try emitter.emitLogitCap(
                inputSlot: SmeltFixedSlot.logitsBuf.rawValue,
                outputSlot: SmeltFixedSlot.logitsBuf.rawValue,
                count: cfg.vocabSize,
                cap: logitCap,
                comment: "Logit capping"
            )
        }

        // Optional post projection is part of the same graph primitive.
        // EAGLE requests it; target-seeded MTP leaves it absent.
        if let postWidth = cfg.resolvedInputFusion?.postProjectionWidth {
            let postEntry = try requireWeight("post_projection_weight", from: weightEntries)
            lines.append(emitter.emitComment(
                cfg.backboneHiddenSize != nil
                    ? "Post-projection (drafter hidden → backbone output)"
                    : "Post-projection (stack hidden → fused output)"
            ))
            lines += try emitter.emitMatvec(
                weightEntry: postEntry,
                weightsSlot: weightsSlot,
                inputSlot: normOutSlot,
                outputSlot: SmeltFixedSlot.hiddenB.rawValue,
                rows: postWidth, cols: hidden, groupSize: groupSize,
                comment: "Post-projection matmul"
            )
            emitter.recordTraceMarker(
                label: "post_projection_out",
                bufferSlot: SmeltFixedSlot.hiddenB.rawValue
            )
        }

        // --- Argmax ---
        lines += try emitter.emitArgmax(
            inputSlot: SmeltFixedSlot.logitsBuf.rawValue,
            outputSlot: SmeltFixedSlot.argmaxBuf.rawValue,
            count: cfg.vocabSize,
            comment: "Argmax"
        )

        // Close function
        lines.append("}")

        // Run optimization passes and rebuild binary records
        emitter.optimizeAndRebuildRecords()

        return GenerateResult(
            source: lines.joined(separator: "\n"),
            dispatchRecords: emitter.dispatchRecords,
            traceMarkers: emitter.buildTraceMarkers(),
            pipelineNames: emitter.buildPipelineNames(),
            namedPipelineNames: emitter.namedPipelines,
            namedPipelineUses: emitter.namedPipelineUses,
            optimizationStats: emitter.optimizationStats,
            isHeadlessTrunkABI: false  // the fp16 token-in / LM-head path, not a headless trunk
        )
    }

    private static func requireAttentionConfig(
        for layerType: SmeltLayerType,
        from config: SmeltConfig
    ) throws -> SmeltAttentionConfig {
        guard let attn = config.attentionConfig(for: layerType) else {
            throw SmeltEmitError.missingConfig(
                detail: "Missing attention config for layer type '\(layerType.rawValue)'"
            )
        }
        return attn
    }

    private static func resolveRoPESlots(
        for attn: SmeltAttentionConfig,
        layerType: SmeltLayerType,
        config: SmeltConfig,
        plan: SmeltBufferPlan
    ) throws -> (cos: Int, sin: Int) {
        let effectiveDim = attn.effectiveRopeDim(default: config.ropeDim)
        let freqDim: Int?
        if layerType != .attention, effectiveDim < attn.headDim {
            freqDim = attn.headDim
        } else {
            freqDim = nil
        }
        let params = SmeltRoPEParams(
            theta: attn.ropeTheta,
            dim: effectiveDim,
            freqDim: freqDim,
            scaling: attn.ropeScaling,
            layout: attn.effectiveRoPETableLayout(blockTopology: config.blockTopology)
        )
        if let pair = plan.ropeTablePairs.first(where: { $0.params == params }) {
            return (pair.cosSlot, pair.sinSlot)
        }
        if plan.ropeTablePairs.count <= 1 {
            return (plan.ropeCosSlot, plan.ropeSinSlot)
        }
        let freqDimText = freqDim.map(String.init) ?? "nil"
        throw SmeltEmitError.unsupported(
            detail: "No RoPE table pair allocated for theta=\(attn.ropeTheta), dim=\(effectiveDim), freq_dim=\(freqDimText)"
        )
    }

    // MARK: - FFN

    private static func emitFFN(
        layerIndex: Int,
        config: SmeltConfig,
        weightEntries: [String: SmeltWeightEntry],
        weightsSlot: Int,
        groupSize: Int,
        ffnDownFp32Slot: Int,
        projectionActivationPlanesSlot: Int,
        projectionActivationScalesSlot: Int,
        kernelPlan: SmeltKernelPlan,
        traceMode: SmeltTraceMode,
        emitter: inout SmeltCodeEmitter
    ) throws -> [String] {
        switch config.ffn.activation {
        case .swiglu:
            return try emitSwiGLU(
                layerIndex: layerIndex,
                config: config,
                weightEntries: weightEntries,
                weightsSlot: weightsSlot,
                groupSize: groupSize,
                ffnDownFp32Slot: ffnDownFp32Slot,
                projectionActivationPlanesSlot: projectionActivationPlanesSlot,
                projectionActivationScalesSlot: projectionActivationScalesSlot,
                kernelPlan: kernelPlan,
                traceMode: traceMode,
                emitter: &emitter
            )
        case .geglu:
            return try emitGeGLU(
                layerIndex: layerIndex,
                config: config,
                weightEntries: weightEntries,
                weightsSlot: weightsSlot,
                groupSize: groupSize,
                ffnDownFp32Slot: ffnDownFp32Slot,
                kernelPlan: kernelPlan,
                emitter: &emitter
            )
        }
    }

    /// Emit SwiGLU FFN: fused gate+up+SwiGLU, then down proj.
    private static func emitSwiGLU(
        layerIndex: Int,
        config: SmeltConfig,
        weightEntries: [String: SmeltWeightEntry],
        weightsSlot: Int,
        groupSize: Int,
        ffnDownFp32Slot: Int,
        projectionActivationPlanesSlot: Int,
        projectionActivationScalesSlot: Int,
        kernelPlan: SmeltKernelPlan,
        traceMode: SmeltTraceMode,
        emitter: inout SmeltCodeEmitter
    ) throws -> [String] {
        let hidden = config.hiddenSize
        let ffnDim = config.ffnDim(for: layerIndex)
        let normOutSlot = SmeltFixedSlot.normOutBuf.rawValue
        var lines: [String] = []

        let gateName = SmeltKernelConsumerNaming.ffnGateWeight(layerIndex: layerIndex)
        let upName = SmeltKernelConsumerNaming.ffnUpWeight(layerIndex: layerIndex)
        let gateEntry = try requireWeight(gateName, from: weightEntries)
        let upEntry = try requireWeight(upName, from: weightEntries)

        let ffnInputBank = config.projectionBank(
            source: .ffnInput,
            containing: [.ffnGate, .ffnUp]
        )
        var signedViewLines: [String]?
        if let activationView = ffnInputBank?.activationView,
           ffnInputBank?.usesActivationView(at: layerIndex) == true,
           projectionActivationPlanesSlot >= 0,
           projectionActivationScalesSlot >= 0 {
            signedViewLines = try emitter.emitSignedBitplaneGateUpSwigluIfPossible(
                view: activationView,
                gateEntry: gateEntry,
                upEntry: upEntry,
                weightsSlot: weightsSlot,
                inputSlot: normOutSlot,
                planesSlot: projectionActivationPlanesSlot,
                activationScalesSlot: projectionActivationScalesSlot,
                outputSlot: SmeltFixedSlot.ffnIntBuf.rawValue,
                rows: ffnDim,
                cols: hidden,
                producerComment: "CAM ffn-input activation view",
                consumerComment: "FFN low-bit gate+up+SwiGLU (signed g128)"
            )
            if signedViewLines == nil {
                signedViewLines = try emitter
                    .emitSignedBitplaneStagedGateUpSwigluIfPossible(
                        view: activationView,
                        gateEntry: gateEntry,
                        upEntry: upEntry,
                        weightsSlot: weightsSlot,
                        inputSlot: normOutSlot,
                        planesSlot: projectionActivationPlanesSlot,
                        activationScalesSlot: projectionActivationScalesSlot,
                        gateOutputSlot: SmeltFixedSlot.ffnGateBuf.rawValue,
                        upOutputSlot: SmeltFixedSlot.ffnUpBuf.rawValue,
                        outputSlot: SmeltFixedSlot.ffnIntBuf.rawValue,
                        rows: ffnDim,
                        cols: hidden,
                        producerComment: "CAM ffn-input activation view",
                        consumerComment: "FFN staged low-bit gate/up projections"
                    )
            }
        }

        // Family via the ONE gateway: the fused gate+up+SwiGLU kernel is used iff BOTH weights
        // authorize the same fused-SwiGLU family (u4_lut/affine_u4); else the separate
        // (gateway-routed) matvecs below.
        let gateUpFamily = emitter.bothFusedFamily(
            gateEntry, upEntry, shape: .gemv, fusion: .gateUpSwiglu)
        let exactTernaryBankLines = gateUpFamily == .ternary2
            ? try emitter.emitSignedTernaryAffineBankGateUpSwigluIfPossible(
                gateEntry: gateEntry,
                upEntry: upEntry,
                weightsSlot: weightsSlot,
                inputSlot: normOutSlot,
                gateOutputSlot: SmeltFixedSlot.ffnGateBuf.rawValue,
                upOutputSlot: SmeltFixedSlot.ffnUpBuf.rawValue,
                outputSlot: SmeltFixedSlot.ffnIntBuf.rawValue,
                rows: ffnDim,
                cols: hidden,
                comment: "CAM ffn-input exact ternary projection bank"
            )
            : nil
        if let signedViewLines {
            lines += signedViewLines
            emitter.recordTraceMarker(
                label: "L\(layerIndex).ffn_int",
                bufferSlot: SmeltFixedSlot.ffnIntBuf.rawValue
            )
        } else if gateUpFamily == .lutU4, let gateLutOff = gateEntry.lutOffset, let upLutOff = upEntry.lutOffset
        {
            // Fused: gate_proj + up_proj + SwiGLU in one dispatch → ffnIntBuf
            lines += try emitter.emitFusedGateUpSwiglu(
                gateIndicesSlot: weightsSlot, gateIndicesOffset: gateEntry.offset,
                gateLutSlot: weightsSlot, gateLutOffset: gateLutOff,
                upIndicesSlot: weightsSlot, upIndicesOffset: upEntry.offset,
                upLutSlot: weightsSlot, upLutOffset: upLutOff,
                inputSlot: normOutSlot,
                outputSlot: SmeltFixedSlot.ffnIntBuf.rawValue,
                rows: ffnDim, cols: hidden, groupSize: groupSize,
                comment: "FFN fused gate+up+SwiGLU"
            )
            emitter.recordTraceMarker(
                label: "L\(layerIndex).ffn_int",
                bufferSlot: SmeltFixedSlot.ffnIntBuf.rawValue
            )
        } else if gateUpFamily == .binary1 {
            lines += try emitter.emitSignedBinaryGateUpSwiglu(
                gateEntry: gateEntry,
                upEntry: upEntry,
                weightsSlot: weightsSlot,
                inputBinding: SmeltBufferBinding(slot: normOutSlot, index: 4),
                outputBinding: SmeltBufferBinding(
                    slot: SmeltFixedSlot.ffnIntBuf.rawValue, index: 5),
                rows: ffnDim,
                cols: hidden,
                comment: "FFN fused gate+up+SwiGLU (binary g128)"
            )
            emitter.recordTraceMarker(
                label: "L\(layerIndex).ffn_int",
                bufferSlot: SmeltFixedSlot.ffnIntBuf.rawValue
            )
        } else if let exactTernaryBankLines {
            lines += exactTernaryBankLines
            emitter.recordTraceMarker(
                label: "L\(layerIndex).ffn_int",
                bufferSlot: SmeltFixedSlot.ffnIntBuf.rawValue
            )
        } else if gateUpFamily == .ternary2 {
            lines += try emitter.emitSignedTernaryAffineGateUpSwiglu(
                gateEntry: gateEntry,
                upEntry: upEntry,
                weightsSlot: weightsSlot,
                inputBinding: SmeltBufferBinding(slot: normOutSlot, index: 6),
                outputBinding: SmeltBufferBinding(
                    slot: SmeltFixedSlot.ffnIntBuf.rawValue, index: 7),
                rows: ffnDim,
                cols: hidden,
                comment: "FFN fused gate+up+SwiGLU (MLX-exact ternary g128)"
            )
            emitter.recordTraceMarker(
                label: "L\(layerIndex).ffn_int",
                bufferSlot: SmeltFixedSlot.ffnIntBuf.rawValue
            )
        } else if gateUpFamily == .affineU4,
                  let gateScales = gateEntry.scalesOffset, let gateBiases = gateEntry.biasesOffset,
                  let upScales = upEntry.scalesOffset, let upBiases = upEntry.biasesOffset,
                  // Entry-resolved group sizes must agree (per-tensor group
                  // sizes are possible) — the fused kernel bakes ONE group size.
                  (gateEntry.groupSize ?? groupSize) == (upEntry.groupSize ?? groupSize)
        {
            // Fused affine: gate_proj + up_proj + SwiGLU in one dispatch → ffnIntBuf
            lines += try emitter.emitFusedAffineGateUpSwiglu(
                gateWeightsSlot: weightsSlot, gateWeightsOffset: gateEntry.offset,
                gateScalesSlot: weightsSlot, gateScalesOffset: gateScales,
                gateBiasesSlot: weightsSlot, gateBiasesOffset: gateBiases,
                upWeightsSlot: weightsSlot, upWeightsOffset: upEntry.offset,
                upScalesSlot: weightsSlot, upScalesOffset: upScales,
                upBiasesSlot: weightsSlot, upBiasesOffset: upBiases,
                inputSlot: normOutSlot,
                outputSlot: SmeltFixedSlot.ffnIntBuf.rawValue,
                rows: ffnDim, cols: hidden,
                groupSize: gateEntry.groupSize ?? groupSize,
                comment: "FFN fused gate+up+SwiGLU (affine)"
            )
            emitter.recordTraceMarker(
                label: "L\(layerIndex).ffn_int",
                bufferSlot: SmeltFixedSlot.ffnIntBuf.rawValue
            )
        } else {
            // Fallback: separate gate, up, swiglu dispatches
            lines += try emitter.emitMatvec(
                weightEntry: gateEntry,
                weightsSlot: weightsSlot,
                inputSlot: normOutSlot,
                outputSlot: SmeltFixedSlot.ffnGateBuf.rawValue,
                rows: ffnDim, cols: hidden, groupSize: groupSize,
                comment: "FFN gate projection"
            )
            emitter.recordTraceMarker(
                label: "L\(layerIndex).ffn_gate",
                bufferSlot: SmeltFixedSlot.ffnGateBuf.rawValue
            )
            lines += try emitter.emitMatvec(
                weightEntry: upEntry,
                weightsSlot: weightsSlot,
                inputSlot: normOutSlot,
                outputSlot: SmeltFixedSlot.ffnUpBuf.rawValue,
                rows: ffnDim, cols: hidden, groupSize: groupSize,
                comment: "FFN up projection"
            )
            emitter.recordTraceMarker(
                label: "L\(layerIndex).ffn_up",
                bufferSlot: SmeltFixedSlot.ffnUpBuf.rawValue
            )
            lines += try emitter.emit(SmeltDispatch(
                pipeline: .swigluFused,
                buffers: [
                    SmeltBufferBinding(
                        slot: SmeltFixedSlot.ffnGateBuf.rawValue, index: 0
                    ),
                    SmeltBufferBinding(
                        slot: SmeltFixedSlot.ffnUpBuf.rawValue, index: 1
                    ),
                    SmeltBufferBinding(
                        slot: SmeltFixedSlot.ffnIntBuf.rawValue, index: 2
                    ),
                ],
                constants: [
                    SmeltConstantBinding(
                        expression: "\(ffnDim)", type: .uint32, index: 3
                    ),
                ],
                dispatch: .threads(
                    width: ffnDim, height: 1, depth: 1,
                    tgWidth: min(ffnDim, 1024), tgHeight: 1, tgDepth: 1
                ),
                comment: "SwiGLU fused"
            ))
            emitter.recordTraceMarker(
                label: "L\(layerIndex).ffn_int",
                bufferSlot: SmeltFixedSlot.ffnIntBuf.rawValue
            )
        }

        // Down projection: values can exceed FP16 range before the following RMSNorm.
        let downName = SmeltKernelConsumerNaming.ffnDownWeight(layerIndex: layerIndex)
        let downEntry = try requireWeight(downName, from: weightEntries)
        let downOutputSlot = ffnDownFp32Slot >= 0 && downEntry.dtype == .fp16
            ? ffnDownFp32Slot
            : SmeltFixedSlot.ffnDownBuf.rawValue
        var lowBitDownLines: [String]?
        if let downBank = config.projectionBank(
            source: .ffnIntermediate,
            containing: [.ffnDown]
        ),
           let activationView = downBank.activationView,
           downBank.usesActivationView(at: layerIndex),
           projectionActivationPlanesSlot >= 0,
           projectionActivationScalesSlot >= 0,
           downEntry.dtype == .binary1 || downEntry.dtype == .ternary2 {
            lines += try emitter.emitSignedActivationView(
                activationView,
                inputSlot: SmeltFixedSlot.ffnIntBuf.rawValue,
                planesSlot: projectionActivationPlanesSlot,
                scalesSlot: projectionActivationScalesSlot,
                cols: ffnDim,
                comment: "CAM ffn-intermediate activation view"
            )
            lowBitDownLines = try emitter.emitSignedBitplaneMatvecIfPossible(
                view: activationView,
                weightEntry: downEntry,
                weightsSlot: weightsSlot,
                planesSlot: projectionActivationPlanesSlot,
                activationScalesSlot: projectionActivationScalesSlot,
                outputSlot: downOutputSlot,
                rows: hidden,
                cols: ffnDim,
                comment: "FFN low-bit down projection"
            )
        }
        if let lowBitDownLines {
            lines += lowBitDownLines
        } else if ffnDownFp32Slot >= 0 && downEntry.dtype == .fp16 {
            lines += try emitter.emitFP16MatvecFP32Out(
                weightSlot: weightsSlot, weightOffset: downEntry.offset,
                inputSlot: SmeltFixedSlot.ffnIntBuf.rawValue,
                outputSlot: downOutputSlot,
                rows: hidden, cols: ffnDim,
                comment: "FFN down projection (FP32 output)"
            )
        } else {
            lines += try emitter.emitMatvec(
                weightEntry: downEntry,
                weightsSlot: weightsSlot,
                inputSlot: SmeltFixedSlot.ffnIntBuf.rawValue,
                outputSlot: downOutputSlot,
                rows: hidden, cols: ffnDim, groupSize: groupSize,
                comment: "FFN down projection",
                plannedKernelRoute: kernelPlan.route(
                    kind: .ffnDownResidualDecode,
                    context: SmeltKernelLayerConsumerContext(
                        config: config,
                        layerIndex: layerIndex,
                        groupSize: downEntry.groupSize ?? groupSize
                    )
                )
            )
        }
        if !traceMode.usesStrippedOptimizations {
            emitter.recordTraceMarker(
                label: "L\(layerIndex).ffn_down",
                bufferSlot: downOutputSlot
            )
        }

        return lines
    }

    private static func emitGeGLU(
        layerIndex: Int,
        config: SmeltConfig,
        weightEntries: [String: SmeltWeightEntry],
        weightsSlot: Int,
        groupSize: Int,
        ffnDownFp32Slot: Int,
        kernelPlan: SmeltKernelPlan,
        emitter: inout SmeltCodeEmitter
    ) throws -> [String] {
        let hidden = config.hiddenSize
        let ffnDim = config.ffnDim(for: layerIndex)
        let normOutSlot = SmeltFixedSlot.normOutBuf.rawValue
        var lines: [String] = []

        let gateName = SmeltKernelConsumerNaming.ffnGateWeight(layerIndex: layerIndex)
        let upName = SmeltKernelConsumerNaming.ffnUpWeight(layerIndex: layerIndex)
        let downName = SmeltKernelConsumerNaming.ffnDownWeight(layerIndex: layerIndex)
        let gateEntry = try requireWeight(gateName, from: weightEntries)
        let upEntry = try requireWeight(upName, from: weightEntries)

        // Family via the ONE gateway: the fused gate+up+GeGLU kernel is used iff BOTH weights
        // authorize the fused-GeGLU family (affine_u4); else separate matvecs.
        let gateUpFamily = emitter.bothFusedFamily(
            gateEntry, upEntry, shape: .gemv, fusion: .gateUpGeGLU)
        if gateUpFamily == .affineU4,
           let gateScales = gateEntry.scalesOffset, let gateBiases = gateEntry.biasesOffset,
           let upScales = upEntry.scalesOffset, let upBiases = upEntry.biasesOffset,
           // Entry-resolved group sizes must agree (per-tensor group
           // sizes are possible) — the fused kernel bakes ONE group size.
           (gateEntry.groupSize ?? groupSize) == (upEntry.groupSize ?? groupSize)
        {
            lines += try emitter.emitFusedAffineGateUpGeGLU(
                gateWeightsSlot: weightsSlot, gateWeightsOffset: gateEntry.offset,
                gateScalesSlot: weightsSlot, gateScalesOffset: gateScales,
                gateBiasesSlot: weightsSlot, gateBiasesOffset: gateBiases,
                upWeightsSlot: weightsSlot, upWeightsOffset: upEntry.offset,
                upScalesSlot: weightsSlot, upScalesOffset: upScales,
                upBiasesSlot: weightsSlot, upBiasesOffset: upBiases,
                inputSlot: normOutSlot,
                outputSlot: SmeltFixedSlot.ffnIntBuf.rawValue,
                rows: ffnDim, cols: hidden,
                groupSize: gateEntry.groupSize ?? groupSize,
                comment: "FFN fused gate+up+GeGLU (affine)"
            )
        } else {
            lines += try emitter.emitMatvec(
                weightEntry: gateEntry,
                weightsSlot: weightsSlot,
                inputSlot: normOutSlot,
                outputSlot: SmeltFixedSlot.ffnGateBuf.rawValue,
                rows: ffnDim, cols: hidden, groupSize: groupSize,
                comment: "FFN gate projection"
            )
            emitter.recordTraceMarker(
                label: "L\(layerIndex).ffn_gate",
                bufferSlot: SmeltFixedSlot.ffnGateBuf.rawValue
            )
            lines += try emitter.emitMatvec(
                weightEntry: upEntry,
                weightsSlot: weightsSlot,
                inputSlot: normOutSlot,
                outputSlot: SmeltFixedSlot.ffnUpBuf.rawValue,
                rows: ffnDim, cols: hidden, groupSize: groupSize,
                comment: "FFN up projection"
            )
            emitter.recordTraceMarker(
                label: "L\(layerIndex).ffn_up",
                bufferSlot: SmeltFixedSlot.ffnUpBuf.rawValue
            )
            lines += try emitter.emitGeGLU(
                gateSlot: SmeltFixedSlot.ffnGateBuf.rawValue,
                upSlot: SmeltFixedSlot.ffnUpBuf.rawValue,
                outputSlot: SmeltFixedSlot.ffnIntBuf.rawValue,
                count: ffnDim,
                comment: "GeGLU fused"
            )
        }
        emitter.recordTraceMarker(
            label: "L\(layerIndex).ffn_int",
            bufferSlot: SmeltFixedSlot.ffnIntBuf.rawValue
        )
        let downEntry = try requireWeight(downName, from: weightEntries)
        let downOutputSlot = ffnDownFp32Slot >= 0 && downEntry.dtype == .fp16
            ? ffnDownFp32Slot
            : SmeltFixedSlot.ffnDownBuf.rawValue
        if ffnDownFp32Slot >= 0 && downEntry.dtype == .fp16 {
            lines += try emitter.emitFP16MatvecFP32Out(
                weightSlot: weightsSlot, weightOffset: downEntry.offset,
                inputSlot: SmeltFixedSlot.ffnIntBuf.rawValue,
                outputSlot: downOutputSlot,
                rows: hidden, cols: ffnDim,
                comment: "FFN down projection (FP32 output)"
            )
        } else {
            lines += try emitter.emitMatvec(
                weightEntry: downEntry,
                weightsSlot: weightsSlot,
                inputSlot: SmeltFixedSlot.ffnIntBuf.rawValue,
                outputSlot: downOutputSlot,
                rows: hidden, cols: ffnDim, groupSize: groupSize,
                comment: "FFN down projection",
                plannedKernelRoute: kernelPlan.route(
                    kind: .ffnDownResidualDecode,
                    context: SmeltKernelLayerConsumerContext(
                        config: config,
                        layerIndex: layerIndex,
                        groupSize: downEntry.groupSize ?? groupSize
                    )
                )
            )
        }
        emitter.recordTraceMarker(
            label: "L\(layerIndex).ffn_down",
            bufferSlot: downOutputSlot
        )
        return lines
    }

    private static func emitStrippedNormScaleGeGLUFFNIfPossible(
        layerIndex: Int,
        config: SmeltConfig,
        weightEntries: [String: SmeltWeightEntry],
        weightsSlot: Int,
        groupSize: Int,
        preFeedforwardNormOffset: UInt64,
        ffnDownFp32Slot: Int,
        emitter: inout SmeltCodeEmitter
    ) throws -> [String]? {
        guard config.ffn.activation == .geglu else { return nil }

        // Current norm-scale GeGLU decode fusion is not exact against the
        // staged quantized contract on real prompts. Keep the stripped
        // exact path on staged pre-FFN RMSNorm + affine GeGLU until this
        // fusion can be proven exact end-to-end.
        return nil
    }

    private static func emitPerLayerInputsSetup(
        config: SmeltConfig,
        weightEntries: [String: SmeltWeightEntry],
        weightsSlot: Int,
        tokenIdSlot: Int,
        groupSize: Int,
        quantizeEmbedding: Bool,
        emitter: inout SmeltCodeEmitter
    ) throws -> [String] {
        let hidden = config.hiddenSize
        let perLayerHidden = config.hiddenSizePerLayerInput
        let perLayerTotalDim = config.numLayers * perLayerHidden
        let perLayerInputsSlot = SmeltFixedSlot.perLayerInputsBuf.rawValue
        let perLayerScratchSlot = SmeltFixedSlot.perLayerScratchBuf.rawValue
        var lines: [String] = []

        let perLayerEmbedEntry = try requireWeight(
            SmeltCanonicalTensorNames.embedTokensPerLayer, from: weightEntries
        )
        if quantizeEmbedding, perLayerEmbedEntry.dtype == .u4Lut, let lutOff = perLayerEmbedEntry.lutOffset {
            lines += try emitter.emitLUTEmbeddingGather(
                indicesSlot: weightsSlot, indicesOffset: perLayerEmbedEntry.offset,
                lutSlot: weightsSlot, lutOffset: lutOff,
                tokenIdSlot: tokenIdSlot,
                outputSlot: perLayerInputsSlot,
                hiddenSize: perLayerTotalDim, groupSize: groupSize,
                comment: "Per-layer token inputs (quantized gather)"
            )
        } else if quantizeEmbedding,
                  perLayerEmbedEntry.dtype == .affineU4,
                  let scalesOff = perLayerEmbedEntry.scalesOffset,
                  let biasesOff = perLayerEmbedEntry.biasesOffset {
            lines += try emitter.emitAffineEmbeddingGather(
                weightsSlot: weightsSlot, weightsOffset: perLayerEmbedEntry.offset,
                scalesSlot: weightsSlot, scalesOffset: scalesOff,
                biasesSlot: weightsSlot, biasesOffset: biasesOff,
                tokenIdSlot: tokenIdSlot,
                outputSlot: perLayerInputsSlot,
                hiddenSize: perLayerTotalDim, groupSize: groupSize,
                comment: "Per-layer token inputs (affine quantized gather)"
            )
        } else if perLayerEmbedEntry.dtype == .binary1
                    || perLayerEmbedEntry.dtype == .ternary2 {
            lines += try emitter.emitSignedEmbeddingGather(
                weightEntry: perLayerEmbedEntry,
                weightsSlot: weightsSlot,
                tokenIdSlot: tokenIdSlot,
                outputSlot: perLayerInputsSlot,
                hiddenSize: perLayerTotalDim,
                comment: "Per-layer token inputs (native signed gather)"
            )
        } else if perLayerEmbedEntry.dtype == .turboQuantH,
                  let codebookOff = perLayerEmbedEntry.codebookOffset,
                  let codesPerRow = perLayerEmbedEntry.packedRowStride {
            lines += try emitter.emitTurboQuantHEmbeddingGather(
                codesSlot: weightsSlot, codesOffset: perLayerEmbedEntry.offset,
                codebookSlot: weightsSlot, codebookOffset: codebookOff,
                tokenIdSlot: tokenIdSlot,
                outputSlot: perLayerInputsSlot,
                hiddenSize: perLayerTotalDim, codesPerRow: codesPerRow,
                comment: "Per-layer token inputs (turbo_quant_h gather)"
            )
        } else {
            lines += try emitter.emitEmbeddingGather(
                weightSlot: weightsSlot, weightOffset: perLayerEmbedEntry.offset,
                tokenIdSlot: tokenIdSlot,
                outputSlot: perLayerInputsSlot,
                hiddenSize: perLayerTotalDim,
                comment: "Per-layer token inputs"
            )
        }
        lines += try emitter.emitScalarMul(
            inputSlot: perLayerInputsSlot,
            outputSlot: perLayerInputsSlot,
            scalar: Float(perLayerHidden).squareRoot(),
            count: perLayerTotalDim,
            comment: "Per-layer token input scale"
        )

        lines += try emitter.emitMatvec(
            weightEntry: try requireWeight("per_layer_model_projection_weight", from: weightEntries),
            weightsSlot: weightsSlot,
            inputSlot: SmeltFixedSlot.hiddenA.rawValue,
            outputSlot: perLayerScratchSlot,
            rows: perLayerTotalDim, cols: hidden, groupSize: groupSize,
            comment: "Per-layer model projection"
        )
        lines += try emitter.emitScalarMul(
            inputSlot: perLayerScratchSlot,
            outputSlot: perLayerScratchSlot,
            scalar: 1.0 / Float(hidden).squareRoot(),
            count: perLayerTotalDim,
            comment: "Per-layer model projection scale"
        )
        lines += try AttentionPlugin.emitPerHeadNorm(
            emitter: &emitter,
            dataSlot: perLayerScratchSlot,
            numHeads: config.numLayers,
            weightName: "per_layer_projection_norm_weight",
            weightsSlot: weightsSlot,
            weightEntries: weightEntries,
            headDim: perLayerHidden,
            eps: config.rmsEps,
            mode: .weight,
            comment: "Per-layer projection RMS norm"
        )
        lines += try emitter.emitElementwiseAdd(
            inputASlot: perLayerScratchSlot,
            inputBSlot: perLayerInputsSlot,
            outputSlot: perLayerInputsSlot,
            count: perLayerTotalDim,
            comment: "Combine per-layer inputs"
        )
        lines += try emitter.emitScalarMul(
            inputSlot: perLayerInputsSlot,
            outputSlot: perLayerInputsSlot,
            scalar: 0.70710677,
            count: perLayerTotalDim,
            comment: "Per-layer input scale"
        )
        emitter.recordTraceMarker(
            label: "per_layer_inputs",
            bufferSlot: perLayerInputsSlot
        )
        return lines
    }

    private static func emitPerLayerResidualBranch(
        layerIndex: Int,
        config: SmeltConfig,
        weightEntries: [String: SmeltWeightEntry],
        weightsSlot: Int,
        groupSize: Int,
        emitter: inout SmeltCodeEmitter,
        traceMode: SmeltTraceMode
    ) throws -> [String] {
        let hidden = config.hiddenSize
        let perLayerHidden = config.hiddenSizePerLayerInput
        let perLayerOffset = UInt64(layerIndex * perLayerHidden * 2)
        var lines: [String] = []

        lines += try emitter.emitMatvecVar(
            weightEntry: try requireWeight("layers_\(layerIndex)_per_layer_input_gate_weight", from: weightEntries),
            weightsSlot: weightsSlot,
            inputSlotVar: "alt",
            outputSlot: SmeltFixedSlot.ffnGateBuf.rawValue,
            rows: perLayerHidden, cols: hidden, groupSize: groupSize,
            comment: "Per-layer input gate"
        )
        emitter.recordTraceMarker(
            label: "L\(layerIndex).per_layer_gate",
            bufferSlot: SmeltFixedSlot.ffnGateBuf.rawValue
        )
        lines += try emitter.emitGeGLU(
            gateSlot: SmeltFixedSlot.ffnGateBuf.rawValue,
            upSlot: SmeltFixedSlot.perLayerInputsBuf.rawValue,
            upOffset: perLayerOffset,
            outputSlot: SmeltFixedSlot.ffnIntBuf.rawValue,
            count: perLayerHidden,
            comment: "Per-layer GELU x residual input"
        )
        emitter.recordTraceMarker(
            label: "L\(layerIndex).per_layer_int",
            bufferSlot: SmeltFixedSlot.ffnIntBuf.rawValue
        )
        lines += try emitter.emitMatvec(
            weightEntry: try requireWeight("layers_\(layerIndex)_per_layer_projection_weight", from: weightEntries),
            weightsSlot: weightsSlot,
            inputSlot: SmeltFixedSlot.ffnIntBuf.rawValue,
            outputSlot: SmeltFixedSlot.normOutBuf.rawValue,
            rows: hidden, cols: perLayerHidden, groupSize: groupSize,
            comment: "Per-layer projection"
        )
        emitter.recordTraceMarker(
            label: "L\(layerIndex).per_layer_proj",
            bufferSlot: SmeltFixedSlot.normOutBuf.rawValue
        )
        let postPerLayerNormOffset = try requireWeight(
            "layers_\(layerIndex)_post_per_layer_input_norm_weight",
            from: weightEntries
        ).offset
        lines += try emitter.emitRMSNorm1PW(
            inputSlot: SmeltFixedSlot.normOutBuf.rawValue,
            weightSlot: weightsSlot,
            weightOffset: postPerLayerNormOffset,
            outputSlot: SmeltFixedSlot.residualBuf.rawValue,
            dim: hidden, eps: config.rmsEps,
            comment: "Post per-layer input norm"
        )
        emitter.recordTraceMarker(
            label: "L\(layerIndex).post_per_layer_norm",
            bufferSlot: SmeltFixedSlot.residualBuf.rawValue
        )
        lines += try emitter.emitElementwiseAddVar(
            inputAVar: "alt",
            inputBSlot: SmeltFixedSlot.residualBuf.rawValue,
            outputVar: "alt", count: hidden,
            comment: "Per-layer residual add"
        )
        emitter.recordTraceMarker(
            label: "L\(layerIndex).post_per_layer_residual",
            bufferSlot: SmeltFixedSlot.hiddenA.rawValue
        )
        return lines
    }
}
